"""empty message

Revision ID: 11c19afc68fe
Revises: 
Create Date: 2017-02-20 23:46:13.991617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c19afc68fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_comments', sa.Column('comment_line', sa.Text(), nullable=True))
    op.add_column('product_comments', sa.Column('sharing_image_links', sa.Text(), nullable=True))
    op.add_column('product_comments', sa.Column('user_nickname', sa.String(length=64), nullable=True))
    op.drop_column('product_comments', 'usernickname')
    op.drop_column('product_comments', 'commentline')
    op.drop_column('product_comments', 'sharelink')
    op.add_column('product_skus', sa.Column('stocks_for_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_skus', 'stocks_for_order')
    op.add_column('product_comments', sa.Column('sharelink', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product_comments', sa.Column('commentline', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('product_comments', sa.Column('usernickname', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('product_comments', 'user_nickname')
    op.drop_column('product_comments', 'sharing_image_links')
    op.drop_column('product_comments', 'comment_line')
    # ### end Alembic commands ###
