"""add stocks to invertory

Revision ID: 168b57a7f3a2
Revises: b8df94472a90
Create Date: 2017-02-22 16:07:22.383775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168b57a7f3a2'
down_revision = 'b8df94472a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('stocks', sa.Integer(), nullable=True))
    op.drop_column('product_skus', 'stocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('stocks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('inventories', 'stocks')
    # ### end Alembic commands ###
