"""add case_ids to products

Revision ID: 1e3b94c19549
Revises: 7d10f98a4ff1
Create Date: 2017-02-21 16:13:05.048991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3b94c19549'
down_revision = '7d10f98a4ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('case_ids', sa.JSON(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'case_ids')

