"""add created_at to productcategory

Revision ID: 4a5bfa3e49d8
Revises: f11ad2dbc427
Create Date: 2017-03-30 12:48:12.590170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5bfa3e49d8'
down_revision = 'f11ad2dbc427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_categories', 'updated_at')
    op.drop_column('product_categories', 'created_at')
    # ### end Alembic commands ###
