"""remove share_stocks

Revision ID: 55c2b7091e1c
Revises: ab10aa8faac9
Create Date: 2017-03-08 14:14:30.985904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c2b7091e1c'
down_revision = 'ab10aa8faac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'share_stocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('share_stocks', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
