"""add length and width to products

Revision ID: 7d54e0aab647
Revises: 55c2b7091e1c
Create Date: 2017-03-16 16:26:19.661125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d54e0aab647'
down_revision = '55c2b7091e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('width', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'width')
    op.drop_column('products', 'length')
    # ### end Alembic commands ###
