"""cancel the relationship between the category and the feature

Revision ID: 849981dd4bf5
Revises: 4a5bfa3e49d8
Create Date: 2017-03-31 10:14:37.773267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849981dd4bf5'
down_revision = '4a5bfa3e49d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sku_features_product_category_id_fkey', 'sku_features', type_='foreignkey')
    op.drop_column('sku_features', 'product_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku_features', sa.Column('product_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sku_features_product_category_id_fkey', 'sku_features', 'product_categories', ['product_category_id'], ['id'])
    # ### end Alembic commands ###
