"""add created_at to product and sku

Revision ID: f11ad2dbc427
Revises: aad400ca8656
Create Date: 2017-03-30 12:37:14.174284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11ad2dbc427'
down_revision = 'aad400ca8656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_skus', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('product_skus', 'updated_at')
    op.drop_column('product_skus', 'created_at')
    # ### end Alembic commands ###
